stages:
- build
- run-example

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build-lib:
    stage: build
    image: ubuntu:devel
    before_script:
    - apt update
    - apt install gcc tup -y
    script:
    - tup
    artifacts:
        paths:
        - build/bin/liblabcutils.a
        - build/obj/*.o
        - build/obj/*.gcno
        - example/build/obj/example.o
        - example/build/obj/example.gcno
        - example/build/bin/example

run-example:
    stage: run-example
    image: ubuntu:devel
    before_script:
    - apt update
    - apt install python3-pip -y
    - pip3 --version
    - pip3 install gcovr
    script:
    - cd example/build/bin/
    - ./example
    - ./example -h
    - gcovr