stages:
- build
- run-example

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build-lib:
    stage: build
    image: ubuntu:latest
    before_script: 
    - echo "What the actual hell, why isn't tup in the repositories"
    - apt update 
    - apt install gcc tup -y
    script:
    - tup
    artifacts:
        paths:
        - build/bin/libLabCUtils.a
        - build/obj/*.o
        - example/build/obj/example.o
        - example/build/bin/example

run-example:
    stage: run-example
    image: ubuntu:latest
    before_script:
    - apt update
    - apt install python3-pip -y
    - pip3 --version
    - pip3 install gcovr
    script:
    - cd examples/build/bin
    - ./example
    - gcovr