stages:
- build
- run-example

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build-lib:
    stage: build
    image: ubuntu:latest
    before_script:
    - apt update
    - apt install software-properties-common -y
    - add-apt-repository universe
    - apt update
    - echo "What the hell, tup is in Ubuntu's repositories but it's sayings it's not when using the docker image"
    - apt install gcc tup -y
    script:
    - tup
    artifacts:
        paths:
        - build/bin/libLabCUtils.a
        - build/obj/*.o
        - example/build/obj/example.o
        - example/build/bin/example

run-example:
    stage: run-example
    image: ubuntu:latest
    before_script:
    - apt update
    - apt install python3-pip -y
    - pip3 --version
    - pip3 install gcovr
    script:
    - cd examples/build/bin
    - ./example
    - gcovr